// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldrowsmnqkiydtxpjhrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkcm93c21ucWtpeWR0eHBqaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTIzMTEsImV4cCI6MjA1NTY2ODMxMX0.b1jd2J04PwYu16YDDcdW69O8hTUT_XWOirbNp_3yjQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);